import '@/styles/globals.scss'

import type { AppProps } from 'next/app'
import Head from 'next/head'
import Link from 'next/link'
import { useQuery } from '@/hooks/useQuery'
import { usePathname } from 'next/navigation'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { navigationMain } from '@/configuration'
import useSWR from 'swr'

type NavMain = {
  title: string
  path: string
  param?: string | undefined
}
export default function App({ Component, pageProps }: AppProps) {
  const [isDark, setIsDark] = useState<boolean>(false)
  const { queryParam } = useQuery()
  const pathName = usePathname()
  const router = useRouter()
  const navigationTop: NavMain[] = navigationMain

  useEffect(() => {}, [pathName, isDark])

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1 className="'text-3xl font-bold">Next Js 13.4 </h1>
      </header>

      <nav>
        <ul>
          {navigationTop.map(({ path, title, param }, idx: number) => {
            return (
              <li key={idx}>
                <Link href={`${path}${param}`} className={pathName === path ? 'isActive' : ''}>
                  {title}
                </Link>
              </li>
            )
          })}
        </ul>
      </nav>
      <h3>{queryParam.get('location')}</h3>
      <h3>{queryParam.get('name')}</h3>

      <Component {...pageProps} />
    </>
  )
}
